- hosts: all
  become: yes
  tasks:
    - name: install Docker
      apt:
        name: docker.io
        state: present
        update_cache: true

    - name: start Docker
      systemd:
        name: docker
        state: started

    - name: ensure net.bridge.bridge-nf-call-ip6tables is set to 1
      sysctl:
        name: net.bridge.bridge-nf-call-ip6tables
        value: 1
        state: present

    - name: ensure net.bridge.bridge-nf-call-iptables is set to 1
      sysctl:
        name: net.bridge.bridge-nf-call-iptables
        value: 1
        state: present

    - name: add Kubernetes' apt repository
      apt_repository:
        name: Kubernetes
        description: Kubernetes apt repository
        repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
        state: present

    - name: install kubelet
      apt:
          name: kubelet
          state: present
          update_cache: true

    - name: install kubeadm
      apt:
          name: kubeadm
          state: present

    - name: start kubelet
      systemd:
         name: kubelet
         enabled: yes
         state: started

- hosts: master
  become: yes
  tasks:
    - name: install kubectl
      apt:
        name: kubectl
        state: present